apiVersion: v1
kind: Service
metadata:
  name: my-service-metallb
  labels:
    app: myapp
    type: front-end
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: myapp
    type: front-end
  type: LoadBalancer
